const express = require('express');
const app = express();
const fs = require("fs");

let response = [{
    id: 0,
    ip: '127.0.0.1',
    task: 1,
    workload: 0.0 // 0.0 means inactive, 1.0 means too much to do
}];
// enables Bot #0
let data = {
    id: 0,
    status: true
};

fs.readFile('Datei.txt', function(err, data) {
    if (err) throw err;
    text = data.toString();
});
app.get('/', function(req, res) {
    res.send(text);
});

app.listen(3000, function() {
    console.log('Example Hello_World listening on port 3000!');
});
/*
let response = [{
    id: 0,
    type: 'hash-md5',
    data: {
        input: 'woot',
        output: null // Not computed yet, String if computed
    }
}];
let data = {
    type: 'hash-md5',
    data: {
        input: 'woot' // output is generated by Bots
    }
};
